// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import StarRatingController from "./star_rating_controller"
application.register("star-rating", StarRatingController)

import TypedController from "./typed_controller"
application.register("typed", TypedController)

import EventController from "./event_controller"
application.register("event", EventController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)
